# This workflow creates a .tar.gz and a .zip packages for the latest release

name: Publish tar.gz and zip releases

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pack-n-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Have a tar.gz
      run: |
        pwd
        ls -l
        version=$(cat .VERSION)
        git archive --format tar.gz --prefix TheToolsProject-$version/ master > /tmp/TheToolsProject-$version.tar.gz
    - name: Have a zip
      run: |
        cd ${GITHUB_WORKSPACE}
        version=$(cat .VERSION)
        git archive --format zip --prefix TheToolsProject-$version/ master > /tmp/TheToolsProject-$version.tar.gz
